name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Build the Docker image
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: build the Docker image
        run: docker-compose up -d --build

      # - name: deploy using kubernetes
      #   run: |
      #     kubectl apply -f k8s-node-app/starwars.deployment.yml
      #     kubectl apply -f k8s-node-app/starwars.deployment.yml
