name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Build the Docker image
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # - name: build the Docker image
      #   run: docker build . -t starwarsapp

      - name: deploy using kubernetes
        run: kubectl apply -f k8s-node-app/starwars.deployment.yml
          kubectl apply -f k8s-node-app/starwars.deployment.yml

  # deploy:
  #   needs: build
  #   runs-on: self-hosted

  #   steps:
  #     - name: Checkout files
  #       uses: actions/checkout@v3

  #     - name: Get tag name
  #       uses: starwars:$(date +%s)

  #     - name: install doctl
  #       uses: digitalocean/action-doctl@v2
  #       with:
  #         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  #     - name: Deploy the Docker image to digitalocean
  #       run: doctl compute droplet create --size 512mb --image $(cat tag) --region sfo2 --ssh-keys $(cat ssh-key) --wait --tag-names $(cat tag) --name $(cat tag)
